// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Hardcoded credentials (Cloudflare env vars were causing issues with swapped/wrong values)
const SUPABASE_URL = 'https://ezinpkzlpszzztkcozud.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_Xhp2s62tWwhC6M49p6w_aw_2X2362iI';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});